import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Divider } from "@mui/material";
import { Logo } from '@/components/Logo'
import { Gravels } from '@/components/Gravels';
import { useState } from 'react';
import { Prix } from '@/components/Prix';
import { Orders } from '@/components/Orders';
import { Reports } from '@/components/Reports';
import { Enterprises } from '@/components/Enterprises';
import { Login } from '@/components/Login';
import { Menu } from '@/components/Menu';

export default function Home() {

  const [sect, setSect] = useState('login')

  const getAuthorization = (childName) => {
    setSect(childName)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Logo />
        <Menu sect={sect} retorno={getAuthorization} />
        <Divider className={styles.divider} /><br></br>
        <Login sect={sect} retorno={getAuthorization} />
        <Gravels sect={sect} />
        <Prix sect={sect} />
        <Enterprises sect={sect} />
        <Orders
          sect={sect}
        />

        <Reports sect={sect} />
      </main>
    </>
  )
}

