import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Divider } from "@mui/material";
import { Logo } from '@/components/Logo'
import { Gravels } from '@/components/Gravels';
import { useState } from 'react';
import { Prix } from '@/components/Prix';
import { Orders } from '@/components/Orders';
import { Reports } from '@/components/Reports';
import { Enterprises } from '@/components/Enterprises';
import useSWR from 'swr'
import { Login } from '@/components/Login';
import { Menu } from '@/components/Menu';
import { Loading } from '@/components/Loading';

const fetcher = (...args) => fetch(...args).then((res) => res.json())

export default function Home() {

  const [sect, setSect] = useState('login')

  const getAuthorization = (childName) => {
    setSect(childName)
  }

  const data_gravels = useSWR(`https://pbetonapi.herokuapp.com/api/v1/gravel/gravels`, fetcher)
  const data_gravel_products = useSWR(`https://pbetonapi.herokuapp.com/api/v1/gravel/gravels_products`, fetcher)
  const data_users = useSWR(`https://pbetonapi.herokuapp.com/api/v1/gravel/users`, fetcher)
  const data_trucks = useSWR(`https://pbetonapi.herokuapp.com/api/v1/gravel/trucks`, fetcher)
  const data_centrals = useSWR(`https://pbetonapi.herokuapp.com/api/v1/gravel/centrals`, fetcher)
  const data_enterprises = useSWR(`https://pbetonapi.herokuapp.com/api/v1/gravel/enterprises`, fetcher)


  if (data_gravels.error || data_enterprises.error || data_users.error || data_trucks.error || data_centrals.error || data_gravel_products.error) return (
    <p>... error</p>
  )

  if (!data_gravels.data) return (
    <Loading />
  )

  if (!data_gravel_products.data) return (
    <Loading />
  )

  if (!data_users.data) return (
    <Loading />
  )

  if (!data_trucks.data) return (
    <Loading />
  )

  if (!data_centrals.data) return (
    <Loading />
  )

  if (!data_enterprises.data) return (
    <Loading />
  )





  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Logo />
        <Menu sect={sect} retorno={getAuthorization} />
        <Divider className={styles.divider} /><br></br>
        <Login sect={sect} retorno={getAuthorization} />
        <Gravels sect={sect} data_gravels={data_gravels} data_gravel_products={data_gravel_products} />
        <Prix sect={sect} />
        <Enterprises sect={sect} data_enterprises={data_enterprises} data_users={data_users} data_trucks={data_trucks} />
        <Orders
          sect={sect}
          data_gravels={data_gravels}
          data_enterprises={data_enterprises}
          data_users={data_users}
          data_trucks={data_trucks}
          data_centrals={data_centrals}
        />

        <Reports sect={sect} />
      </main>
    </>
  )
}

